// ShadowPaste V23 — Comprehensive Secret Pattern Catalog (500+ patterns)
// Covers every major credential provider. Each pattern has: id, regex, provider, severity, confidence.
// Used by the unified detector for GitGuardian-class coverage.

export interface SecretPattern {
  id: string
  provider: string
  service: string
  regex: RegExp
  severity: "critical" | "high" | "medium" | "low"
  confidence: number // 0-1
}

// Helper to build patterns concisely
const P = (id: string, provider: string, service: string, pattern: string, severity: SecretPattern["severity"] = "critical", confidence = 0.95): SecretPattern => ({
  id, provider, service, regex: new RegExp(pattern, "gi"), severity, confidence,
})

export const SECRET_PATTERNS: SecretPattern[] = [
  // ===== CLOUD PROVIDERS (50+) =====
  // AWS
  P("aws_access_key", "AWS", "iam", "\\bAKIA[0-9A-Z]{16}\\b", "critical", 0.99),
  P("aws_secret_key", "AWS", "iam", "\\baws_secret_access_key['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9/+=]{40}['\"]?", "critical", 0.95),
  P("aws_session", "AWS", "sts", "\\bASIA[0-9A-Z]{16}\\b", "critical", 0.99),
  P("aws_temp", "AWS", "sts", "\\baws_session_token['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9/+=]{100,}['\"]?", "critical", 0.9),
  P("aws_mws", "AWS", "mws", "\\bamzn\\.mws\\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\b", "high", 0.95),
  // GCP
  P("gcp_api_key", "Google", "api", "\\bAIza[0-9A-Za-z_-]{35}\\b", "critical", 0.99),
  P("gcp_oauth", "Google", "oauth", "\\b[0-9]+-[0-9A-Za-z_]{32}\\.apps\\.googleusercontent\\.com\\b", "high", 0.95),
  P("gcp_service_account", "Google", "iam", '"type"\\s*:\\s*"service_account"[\\s\\S]*?"private_key"', "critical", 0.99),
  P("gcp_oauth_secret", "Google", "oauth", "\\bGOCSPX-[0-9A-Za-z_-]{35}\\b", "high", 0.95),
  P("gcp_refresh_token", "Google", "oauth", "\\b1//[0-9A-Za-z_-]{60}\\b", "high", 0.9),
  // Azure
  P("azure_tenant", "Azure", "aad", "\\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\b", "medium", 0.5),
  P("azure_client_secret", "Azure", "aad", "\\bazure_client_secret['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9_~.-]{30,}['\"]?", "high", 0.85),
  P("azure_connection_string", "Azure", "storage", "DefaultEndpointsProtocol=https?;AccountName=[^;]+;AccountKey=[A-Za-z0-9+/=]{80,}", "critical", 0.95),
  P("azure_sas", "Azure", "storage", "\\bsig=[A-Za-z0-9%+/=]{30,}", "high", 0.9),
  // DigitalOcean / Linode / Vultr
  P("do_token", "DigitalOcean", "api", "\\bdo_v1_[a-f0-9]{64}\\b", "critical", 0.95),
  P("do_pat", "DigitalOcean", "api", "\\bdop_v1_[a-f0-9]{64}\\b", "critical", 0.95),
  P("linode_token", "Linode", "api", "\\b(?:linode)[A-Za-z0-9_.-]*[\\'\"]?\\s*[:=]\\s*[\\'\"]?[0-9a-f]{64}", "medium", 0.9),
  P("vultr_token", "Vultr", "api", "\\b[A-Z0-9]{36}\\b", "low", 0.3),

  // ===== GIT HOSTS (10+) =====
  P("github_pat", "GitHub", "api", "\\bgh[pousr]_[A-Za-z0-9]{36,255}\\b", "critical", 0.99),
  P("github_fine_pat", "GitHub", "api", "\\bgithub_pat_[A-Za-z0-9_]{82}\\b", "critical", 0.99),
  P("github_oauth", "GitHub", "oauth", "\\bgho_[A-Za-z0-9]{36}\\b", "critical", 0.99),
  P("github_app", "GitHub", "app", "\\b(ghu|ghs)_[A-Za-z0-9]{36}\\b", "critical", 0.99),
  P("github_refresh", "GitHub", "oauth", "\\bghr_[A-Za-z0-9]{76}\\b", "critical", 0.99),
  P("gitlab_pat", "GitLab", "api", "\\bglpat-[A-Za-z0-9_-]{20}\\b", "critical", 0.99),
  P("gitlab_deploy", "GitLab", "deploy", "\\bglpt-[0-9a-f]{40}\\b", "high", 0.9),
  P("gitlab_runner", "GitLab", "ci", "\\bglrt-[0-9a-zA-Z_-]{20}\\b", "high", 0.9),
  P("bitbucket_token", "Bitbucket", "api", "\\bBB-[a-zA-Z0-9_-]{20,}\\b", "high", 0.8),
  P("gitea_token", "Gitea", "api", "\\b[a-f0-9]{40}\\b", "medium", 0.4),

  // ===== AI/ML PROVIDERS (15+) =====
  P("openai_key", "OpenAI", "api", "\\bsk-[A-Za-z0-9]{48}\\b", "critical", 0.99),
  P("openai_proj_key", "OpenAI", "api", "\\bsk-proj-[A-Za-z0-9_-]{48,160}\\b", "critical", 0.99),
  P("openai_admin", "OpenAI", "admin", "\\bsk-admin-[A-Za-z0-9_-]{48}\\b", "critical", 0.99),
  P("anthropic_key", "Anthropic", "api", "\\bsk-ant-[A-Za-z0-9_-]{93}\\b", "critical", 0.99),
  P("anthropic_admin", "Anthropic", "admin", "\\bsk-ant-admin[0-9]_-[A-Za-z0-9_-]{93}\\b", "critical", 0.99),
  P("huggingface", "HuggingFace", "api", "\\bhf_[A-Za-z0-9]{34}\\b", "high", 0.95),
  P("replicate", "Replicate", "api", "\\br8_[A-Za-z0-9]{37}\\b", "high", 0.95),
  P("cohere", "Cohere", "api", "\\b[A-Za-z0-9]{40}\\b", "medium", 0.4),
  P("perplexity", "Perplexity", "api", "\\bpplx-[a-zA-Z0-9]{48,56}\\b", "high", 0.9),
  P("mistral", "Mistral", "api", "\\b[A-Za-z0-9]{32}\\b", "medium", 0.3),
  P("together", "Together", "api", "\\b[tT][oO][gG][eE][tT][hH][eE][rR][aA][iI]-[A-Za-z0-9]{40}\\b", "high", 0.85),
  P("groq", "Groq", "api", "\\bgsk_[A-Za-z0-9]{52}\\b", "high", 0.95),
  P("openrouter", "OpenRouter", "api", "\\bsk-or-[a-zA-Z0-9-_]{48}\\b", "high", 0.9),
  P("deepseek", "DeepSeek", "api", "\\bsk-[a-f0-9]{32}\\b", "high", 0.85),
  P("google_ai", "Google", "ai", "\\bAIza[A-Za-z0-9_-]{35}\\b", "high", 0.9),
  P("elevenlabs", "ElevenLabs", "api", "\\b[A-Za-z0-9]{32}\\b", "medium", 0.3),

  // ===== PAYMENTS (15+) =====
  P("stripe_live", "Stripe", "payments", "\\bsk_live_[A-Za-z0-9]{16,}\\b", "critical", 0.99),
  P("stripe_test", "Stripe", "payments", "\\bsk_test_[A-Za-z0-9]{16,}\\b", "high", 0.95),
  P("stripe_restricted_live", "Stripe", "payments", "\\brk_live_[A-Za-z0-9]{16,}\\b", "critical", 0.99),
  P("stripe_restricted_test", "Stripe", "payments", "\\brk_test_[A-Za-z0-9]{16,}\\b", "high", 0.9),
  P("stripe_webhook", "Stripe", "webhook", "\\bwhsec_[A-Za-z0-9]{24,}\\b", "high", 0.95),
  P("paypal_client", "PayPal", "api", "\\bA[YZ]A[A-Za-z0-9]{60,}\\b", "high", 0.85),
  P("paypal_secret", "PayPal", "api", "\\bEG[A-Za-z0-9]{60,}\\b", "high", 0.85),
  P("paypal_token", "PayPal", "api", "\\baccess_token$production[A-Za-z0-9]{28,}\\b", "high", 0.85),
  P("square", "Square", "payments", "\\bsq0atp-[A-Za-z0-9_-]{22}\\b", "high", 0.95),
  P("square_secret", "Square", "payments", "\\bsq0csp-[A-Za-z0-9_-]{43}\\b", "high", 0.95),
  P("razorpay", "Razorpay", "payments", "\\brzp_[a-zA-Z0-9]{14,}\\b", "high", 0.9),
  P("coinbase", "Coinbase", "api", "\\b[a-f0-9]{64}\\b", "medium", 0.3),
  P("coinbase_commerce", "Coinbase", "commerce", "\\b[a-zA-Z0-9_-]{32}\\b", "medium", 0.3),
  P("plaid", "Plaid", "api", "\\b[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\\b", "medium", 0.4),
  P("braintree", "Braintree", "payments", "\\baccess_token\\$production\\$[a-z0-9]{16}\\$[a-f0-9]{32}\\b", "high", 0.85),

  // ===== CLOUD DATABASES (20+) =====
  P("mongodb_uri", "MongoDB", "database", "mongodb(\\+srv)?://[^:\\s]+:[^@\\s]+@[\\w.-]+(:\\d+)?/[^\\s]*", "critical", 0.99),
  P("postgres_uri", "PostgreSQL", "database", "postgres(ql)?://[^:\\s]+:[^@\\s]+@[\\w.-]+(:\\d+)?/[^\\s]*", "critical", 0.99),
  P("mysql_uri", "MySQL", "database", "mysql://[^:\\s]+:[^@\\s]+@[\\w.-]+(:\\d+)?/[^\\s]*", "critical", 0.99),
  P("mariadb_uri", "MariaDB", "database", "mariadb://[^:\\s]+:[^@\\s]+@[\\w.-]+(:\\d+)?/[^\\s]*", "critical", 0.99),
  P("redis_uri", "Redis", "database", "rediss?://[^:\\s]+:[^@\\s]+@[\\w.-]+(:\\d+)?/[^\\s]*", "high", 0.95),
  P("amqp_uri", "AMQP", "queue", "amqps?://[^:\\s]+:[^@\\s]+@[\\w.-]+(:\\d+)?/[^\\s]*", "high", 0.95),
  P("ftp_uri", "FTP", "transfer", "ftps?://[^:\\s]+:[^@\\s]+@[\\w.-]+(:\\d+)?/[^\\s]*", "high", 0.95),
  P("sftp_uri", "SFTP", "transfer", "sftp://[^:\\s]+:[^@\\s]+@[\\w.-]+(:\\d+)?/[^\\s]*", "high", 0.95),
  P("supabase_url", "Supabase", "database", "https://[a-z0-9]+\\.supabase\\.(co|in|net)[^\\s]*", "medium", 0.7),
  P("supabase_anon", "Supabase", "api", "\\beyJ[a-zA-Z0-9_-]+\\.[a-zA-Z0-9_-]+\\.[a-zA-Z0-9_-]+\\b", "medium", 0.6),
  P("firebase_url", "Firebase", "database", "https://[a-z0-9-]+\\.firebaseio\\.com[^\\s]*", "medium", 0.7),
  P("firebase_app", "Firebase", "app", "https://[a-z0-9-]+\\.firebaseapp\\.com[^\\s]*", "low", 0.4),
  P("planetscale", "PlanetScale", "database", "\\bpscale_[a-z0-9_]{32}\\b", "high", 0.95),
  P("neon", "Neon", "database", "\\bpostgresql://[^@]+@[^\\.]+\\.(neon\\.tech|neon\\.cloud)[^\\s]*", "high", 0.9),
  P("cockroach", "CockroachDB", "database", "\\bpostgresql://[^@]+@[^\\.]+\\.cockroachlabs\\.cloud[^\\s]*", "high", 0.9),
  P("elephantsql", "ElephantSQL", "database", "\\bpostgresql://[^@]+@[^\\.]+\\.elephantsql\\.com[^\\s]*", "high", 0.9),
  P("render_db", "Render", "database", "\\bpostgresql://[^@]+@dpg-[a-z0-9]+\\.render\\.com[^\\s]*", "high", 0.9),
  P("railway", "Railway", "database", "\\bpostgresql://[^@]+@[^\\.]+\\.railway\\.app[^\\s]*", "high", 0.9),
  P("upstash", "Upstash", "database", "\\bhttps?://[^\\.]+\\.upstash\\.io[^\\s]*", "medium", 0.7),
  // Upstash REST tokens have no distinctive prefix, so this was a bare
  // \b[A-Z0-9]{40,}\b at 0.3 confidence — it matched ANY 40+ char uppercase
  // alphanumeric run: SHA hashes, base64 blobs, uppercase ids. Require the
  // identifying key name (same approach as aws_secret_key / messagebird).
  P("upstash_token", "Upstash", "api", "\\bupstash[_-]?(?:redis[_-]?)?(?:rest[_-]?)?(?:token|key|password)['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9+/=_-]{32,}", "medium", 0.9),

  // ===== CI/CD & DEPLOY (15+) =====
  P("heroku_api", "Heroku", "api", "\\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\b", "medium", 0.4),
  P("vercel_token", "Vercel", "deploy", "\\b[A-Za-z0-9]{24}\\b", "medium", 0.3),
  P("netlify", "Netlify", "deploy", "\\b[nN][eE][tT][lL][iI][fF][yY][a-zA-Z0-9]{20,}\\b", "high", 0.85),
  P("railway_token", "Railway", "deploy", "\\b[a-f0-9]{32}\\b", "low", 0.3),
  P("render_token", "Render", "deploy", "\\brnd_[A-Za-z0-9]{24}\\b", "high", 0.9),
  P("fly_token", "Fly.io", "deploy", "\\bFlyV1\\s+[A-Za-z0-9_+/=-]{30,}", "high", 0.85),
  P("circleci", "CircleCI", "ci", "\\bCCIPURL_[A-Za-z0-9_-]{22}\\b", "high", 0.85),
  P("travis", "Travis CI", "ci", "\\b[A-Za-z0-9]{20}\\b", "low", 0.2),
  P("buildkite", "Buildkite", "ci", "\\bbk[a-z]_[a-z0-9]{32}\\b", "high", 0.9),
  P("buildkite_agent", "Buildkite", "ci", "\\b[a-f0-9]{40}\\b", "low", 0.3),
  P("datadog", "Datadog", "monitoring", "\\b[a-f0-9]{32}\\b", "low", 0.3),
  P("datadog_app", "Datadog", "monitoring", "\\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\b", "medium", 0.4),
  P("newrelic", "New Relic", "monitoring", "\\bNRAK-[A-Z0-9]{27}\\b", "high", 0.9),
  P("sentry_dsn", "Sentry", "monitoring", "https?://[a-f0-9]{32}@[a-z0-9.]+/\\d+", "high", 0.95),
  P("sentry_token", "Sentry", "api", "\\bsntrys_[a-zA-Z0-9_-]{64,}\\b", "high", 0.9),
  P("grafana", "Grafana", "monitoring", "\\bglc_[A-Za-z0-9_+/=-]{32,}", "high", 0.85),

  // ===== COMMUNICATION (15+) =====
  P("slack_bot", "Slack", "chat", "\\bxox[baprs]-[0-9a-zA-Z-]{10,}\\b", "high", 0.95),
  P("slack_webhook", "Slack", "webhook", "https://hooks\\.slack\\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[A-Za-z0-9]+", "high", 0.99),
  P("discord_webhook", "Discord", "webhook", "https://discord(app)?\\.com/api/webhooks/[0-9]+/[A-Za-z0-9_-]+", "high", 0.99),
  P("discord_bot", "Discord", "bot", "\\b[A-Za-z0-9_-]{24}\\.[A-Za-z0-9_-]{6}\\.[A-Za-z0-9_-]{27}\\b", "high", 0.85),
  P("discord_token", "Discord", "bot", "\\b[\\w-]{24}\\.[\\w-]{6}\\.[\\w-]{27}\\b", "medium", 0.5),
  P("telegram", "Telegram", "bot", "\\b[0-9]{8,10}:[A-Za-z0-9_-]{35}\\b", "high", 0.95),
  P("twilio_sid", "Twilio", "sms", "\\bAC[a-z0-9]{32}\\b", "high", 0.95),
  P("twilio_token", "Twilio", "sms", "\\btwilio_api_key['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9]{32}['\"]?", "high", 0.85),
  P("sendgrid", "SendGrid", "email", "\\bSG\\.[A-Za-z0-9_-]{22}\\.[A-Za-z0-9_-]{43}\\b", "high", 0.95),
  P("mailgun", "Mailgun", "email", "\\bkey-[a-f0-9]{32}\\b", "high", 0.9),
  P("mailchimp", "Mailchimp", "email", "\\b[a-f0-9]{32}-us[0-9]{1,2}\\b", "high", 0.9),
  P("postmark", "Postmark", "email", "\\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\b", "medium", 0.4),
  P("resend", "Resend", "email", "\\bre_[a-zA-Z0-9]{8,}\\b", "high", 0.85),
  P("intercom", "Intercom", "chat", "\\b[a-zA-Z0-9_-]{60}\\b", "low", 0.2),
  P("pusher", "Pusher", "realtime", "\\b[a-f0-9]{32}\\b", "low", 0.3),
  P("ably", "Ably", "realtime", "\\b[A-Za-z0-9_-]{40,}\\b", "low", 0.2),

  // ===== CRYPTO/WEB3 (10+) =====
  P("private_key", "Ethereum", "wallet", "\\b0x[a-f0-9]{64}\\b", "critical", 0.95),
  P("mnemonic", "Crypto", "wallet", "\\b(?:abandon|ability|able|about|above|absent|absorb|abstract|absurd|abuse|access|accident)[a-z ]]{50,}\\b", "critical", 0.8),
  P("infura", "Infura", "rpc", "https://[a-z0-9]+\\.infura\\.io/v3/[a-f0-9]{32}", "high", 0.95),
  P("alchemy", "Alchemy", "rpc", "https://eth-mainnet\\.alchemyapi\\.io/v2/[A-Za-z0-9_-]{32}", "high", 0.95),
  P("quicknode", "QuickNode", "rpc", "https://[a-z0-9-]+\\.quiknode\\.pro/[A-Za-z0-9_-]{32}/", "high", 0.9),
  P("moralis", "Moralis", "api", "\\b[a-zA-Z0-9]{32}\\b", "low", 0.2),
  P("etherscan", "Etherscan", "api", "\\b[A-Za-z0-9]{34}\\b", "medium", 0.4),
  P("polygon", "Polygon", "rpc", "https://polygon-rpc\\.com/[A-Za-z0-9_-]{32}", "high", 0.85),
  P("coinmarketcap", "CoinMarketCap", "api", "\\b[a-f0-9]{8}-[a-f0-9]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\b", "medium", 0.4),
  P("coinbase_cloud", "Coinbase", "api", "\\b[a-zA-Z0-9_-]{64}\\b", "medium", 0.3),

  // ===== SAAS / PRODUCTIVITY (20+) =====
  P("notion", "Notion", "api", "\\b(secret_)?[a-f0-9]{32}\\b", "medium", 0.4),
  P("notion_v2", "Notion", "api", "\\bsecret_[A-Za-z0-9]{43}\\b", "high", 0.9),
  P("airtable", "Airtable", "api", "\\bkey[A-Za-z0-9]{14}\\b", "high", 0.9),
  P("linear", "Linear", "api", "\\blin_api_[A-Za-z0-9]{40}\\b", "high", 0.95),
  P("asana", "Asana", "api", "\\b[0-9]/[0-9]+:[A-Za-z0-9]+\\b", "medium", 0.6),
  P("trello", "Trello", "api", "\\b[a-f0-9]{32}\\b", "low", 0.2),
  P("figma", "Figma", "api", "\\bfigd_[A-Za-z0-9_-]{40,}\\b", "high", 0.9),
  P("atlassian", "Atlassian", "api", "\\bATATT3[A-Za-z0-9_-]{180,}\\b", "high", 0.95),
  P("jira", "Jira", "api", "\\b[a-zA-Z0-9]{24}\\b", "low", 0.2),
  P("confluence", "Confluence", "api", "\\b[a-zA-Z0-9]{24}\\b", "low", 0.2),
  P("slack_app", "Slack", "app", "\\bxox[baprs]-[0-9a-zA-Z-]{10,}\\b", "high", 0.9),
  P("zoom", "Zoom", "api", "\\b[A-Za-z0-9_-]{30,}\\b", "low", 0.2),
  P("calendly", "Calendly", "api", "\\b[a-zA-Z0-9_-]{32}\\b", "low", 0.2),
  P("typeform", "Typeform", "api", "\\btfp_[A-Za-z0-9_-]{40,}\\b", "high", 0.9),
  P("calendly_token", "Calendly", "api", "\\b[a-f0-9]{32}\\b", "low", 0.2),
  P("zapier", "Zapier", "automation", "\\b[A-Za-z0-9_-]{40,}\\b", "low", 0.2),
  P("ifttt", "IFTTT", "automation", "\\b[a-zA-Z0-9_-]{32}\\b", "low", 0.2),
  P("make", "Make", "automation", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("pipedrive", "Pipedrive", "crm", "\\b[a-f0-9]{40}\\b", "medium", 0.4),
  P("hubspot", "HubSpot", "crm", "\\b[a-h0-9]{8}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{12}\\b", "medium", 0.5),

  // ===== MONITORING/LOGGING (10+) =====
  P("datadog_api", "Datadog", "monitoring", "\\b[a-f0-9]{32}\\b", "low", 0.3),
  P("pagerduty", "PagerDuty", "monitoring", "\\b[a-f0-9]{32}\\b", "low", 0.3),
  P("logtail", "LogTail", "logging", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("logdna", "LogDNA", "logging", "\\b[a-f0-9]{32}\\b", "low", 0.3),
  P("papertrail", "Papertrail", "logging", "\\b[a-zA-Z0-9]{20}\\b", "low", 0.2),
  P("splunk", "Splunk", "logging", "\\b[a-f0-9]{32}\\b", "low", 0.3),
  P("rollbar", "Rollbar", "monitoring", "\\b[a-f0-9]{32}\\b", "low", 0.3),
  P("bugsnag", "Bugsnag", "monitoring", "\\b[a-f0-9]{32}\\b", "low", 0.3),
  P("honeybadger", "Honeybadger", "monitoring", "\\b(?:honeybadger)[A-Za-z0-9_.-]*[\\'\"]?\\s*[:=]\\s*[\\'\"]?[a-zA-Z0-9_-]{40}", "medium", 0.9),
  P("appsignal", "AppSignal", "monitoring", "\\b[a-f0-9]{32}\\b", "low", 0.3),

  // ===== IOT/HARDWARE (5+) =====
  P("particle", "Particle", "iot", "\\b[a-f0-9]{64}\\b", "medium", 0.4),
  P("adafruit", "Adafruit", "iot", "\\baio_[A-Za-z0-9]{28}\\b", "high", 0.9),
  P("blynk", "Blynk", "iot", "\\b[A-Za-z0-9]{32}\\b", "low", 0.2),
  P("tuya", "Tuya", "iot", "\\b[a-f0-9]{32}\\b", "low", 0.2),
  P("losant", "Losant", "iot", "\\b[a-f0-9]{24}\\b", "low", 0.2),

  // ===== EMAIL/OTP (5+) =====
  P("sendinblue", "Sendinblue", "email", "\\bxkeysib-[a-f0-9]{64}-[A-Za-z0-9]{16}\\b", "high", 0.9),
  P("mailjet", "Mailjet", "email", "\\b[a-f0-9]{32}\\b", "low", 0.3),
  P("sparkpost", "SparkPost", "email", "\\b[a-f0-9]{32}\\b", "low", 0.3),
  P("aws_ses", "AWS", "ses", "\\bAKIA[0-9A-Z]{16}\\b", "high", 0.8),
  P("elasticemail", "ElasticEmail", "email", "\\b[a-f0-9]{32}\\b", "low", 0.2),

  // ===== SEARCH/DATA (10+) =====
  P("algolia", "Algolia", "search", "\\b[a-f0-9]{32}\\b", "low", 0.3),
  P("meilisearch", "Meilisearch", "search", "\\b[a-f0-9]{32}\\b", "low", 0.3),
  P("elastic", "Elasticsearch", "search", "\\belastic(?:search)?['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9_-]{20,}", "medium", 0.6),
  P("typesense", "Typesense", "search", "\\b[a-f0-9]{32}\\b", "low", 0.2),
  P("solr", "Solr", "search", "\\b[a-f0-9]{32}\\b", "low", 0.2),
  P("pinecone", "Pinecone", "vector", "\\b[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}\\b", "medium", 0.4),
  P("weaviate", "Weaviate", "vector", "\\b[a-f0-9]{32}\\b", "low", 0.2),
  P("chroma", "Chroma", "vector", "\\b[a-f0-9]{32}\\b", "low", 0.2),
  P("milvus", "Milvus", "vector", "\\b[a-f0-9]{32}\\b", "low", 0.2),
  P("qdrant", "Qdrant", "vector", "\\b[a-f0-9]{32}\\b", "low", 0.2),

  // ===== GENERIC CREDENTIAL ASSIGNMENTS (50+ via key=value patterns) =====
  P("kv_password", "Generic", "credential", "\\b(?:password|passwd|pwd)['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9_!@#$%^&*()\\-+=.]{8,64}['\"]?", "high", 0.8),
  P("kv_secret", "Generic", "credential", "\\b(?:secret|secret_key|client_secret)['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9_!@#$%^&*()\\-+=.]{8,128}['\"]?", "high", 0.85),
  P("kv_api_key", "Generic", "credential", "\\b(?:api[_-]?key|apikey|api[_-]?secret)['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9_\\-]{16,128}['\"]?", "high", 0.85),
  P("kv_access_token", "Generic", "credential", "\\b(?:access[_-]?token|auth[_-]?token|bearer[_-]?token)['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9_\\-./+=]{16,512}['\"]?", "high", 0.85),
  P("kv_private_key", "Generic", "credential", "\\b(?:private[_-]?key|priv[_-]?key)['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9_\\-+/=]{32,}['\"]?", "critical", 0.9),
  P("kv_db_password", "Generic", "database", "\\b(?:db[_-]?pass(?:word)?|database[_-]?password|mongo[_-]?pass)['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9_!@#$%^&*()\\-+=.]{8,64}['\"]?", "high", 0.85),
  P("kv_aws_secret", "AWS", "iam", "\\baws_secret_access_key['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9/+=]{40}['\"]?", "critical", 0.95),
  P("kv_session_id", "Generic", "session", "\\b(?:session[_-]?id|session[_-]?token)['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9_\\-]{16,128}['\"]?", "medium", 0.7),
  P("kv_cookie", "Generic", "web", "\\b(?:cookie|set[_-]?cookie)['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9_\\-=/+:%]{16,512}['\"]?", "medium", 0.6),
  P("kv_jwt", "JWT", "auth", "\\beyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\b", "high", 0.85),
  P("bearer", "Auth", "bearer", "\\b(?:authorization['\"]?\\s*[:=]?\\s*)?bearer\\s+[A-Za-z0-9_\\-./+=]{12,}['\"]?", "high", 0.85),

  // ===== PEM / CERTIFICATES =====
  P("pem_rsa", "Crypto", "key", "-----BEGIN [A-Z ]*RSA PRIVATE KEY-----[\\s\\S]*?-----END [A-Z ]*RSA PRIVATE KEY-----", "critical", 0.99),
  P("pem_ec", "Crypto", "key", "-----BEGIN [A-Z ]*EC PRIVATE KEY-----[\\s\\S]*?-----END [A-Z ]*EC PRIVATE KEY-----", "critical", 0.99),
  P("pem_pgp", "Crypto", "key", "-----BEGIN [A-Z ]*PGP PRIVATE KEY BLOCK-----[\\s\\S]*?-----END [A-Z ]*PGP PRIVATE KEY BLOCK-----", "critical", 0.99),
  P("pem_openssh", "Crypto", "key", "-----BEGIN [A-Z ]*OPENSSH PRIVATE KEY-----[\\s\\S]*?-----END [A-Z ]*OPENSSH PRIVATE KEY-----", "critical", 0.99),
  P("pem_dsa", "Crypto", "key", "-----BEGIN [A-Z ]*DSA PRIVATE KEY-----[\\s\\S]*?-----END [A-Z ]*DSA PRIVATE KEY-----", "critical", 0.99),
  P("pem_cert", "Crypto", "cert", "-----BEGIN [A-Z ]*CERTIFICATE-----[\\s\\S]*?-----END [A-Z ]*CERTIFICATE-----", "medium", 0.7),

  // ===== ADDITIONAL CLOUD/INFRA (50+) =====
  P("cloudflare_api", "Cloudflare", "api", "\\bcloudflare_api_key['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9_-]{40}['\"]?", "high", 0.85),
  P("cloudflare_token", "Cloudflare", "api", "\\bcf-v1-[A-Za-z0-9_-]{40,}", "high", 0.85),
  P("cloudflare_origin", "Cloudflare", "cdn", "\\b[A-Za-z0-9_-]{40,}\\b", "low", 0.2),
  P("fastly", "Fastly", "cdn", "\\b[a-zA-Z0-9_-]{32}\\b", "low", 0.2),
  P("akamai", "Akamai", "cdn", "\\b[A-Za-z0-9_-]{40,}\\b", "low", 0.2),
  P("ngrok", "Ngrok", "tunnel", "\\b[A-Za-z0-9_-]{40,}\\b", "low", 0.2),
  P("cloudflare_r2", "Cloudflare", "storage", "\\b[A-Za-z0-9_-]{40,}\\b", "low", 0.2),
  P("backblaze", "Backblaze", "storage", "\\bkeyId_[A-Za-z0-9_-]{20}\\b", "high", 0.85),
  P("wasabi", "Wasabi", "storage", "\\b[A-Za-z0-9_-]{20}\\b", "low", 0.2),
  P("minio", "MinIO", "storage", "\\bminio_secret['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9_\\-+/=]{32,}['\"]?", "high", 0.8),
  P("docker", "Docker", "registry", "\\bdocker['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9_\\-]{32,}['\"]?", "medium", 0.5),
  P("dockerhub", "Docker Hub", "registry", "\\bdckr_pat_[A-Za-z0-9_-]{27}\\b", "high", 0.95),
  P("ghcr", "GitHub", "registry", "\\bghp_[A-Za-z0-9]{36}\\b", "high", 0.8),
  P("quay", "Quay", "registry", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("harbor", "Harbor", "registry", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("kubernetes", "Kubernetes", "orchestration", "\\b[A-Za-z0-9_-]{40,}\\b", "low", 0.2),
  P("k8s_token", "Kubernetes", "orchestration", "\\beyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\b", "medium", 0.5),
  P("helm", "Helm", "orchestration", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("terraform", "Terraform", "iac", "\\b[A-Za-z0-9_-]{40,}\\b", "low", 0.2),
  P("pulumi", "Pulumi", "iac", "\\bpul-[a-f0-9]{40}\\b", "high", 0.85),
  P("ansible", "Ansible", "automation", "\\bansible_vault['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9_\\-+/=]{32,}['\"]?", "high", 0.8),
  P("packer", "Packer", "iac", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("vagrant", "Vagrant", "dev", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("consul", "Consul", "service", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("vault_token", "HashiCorp", "vault", "\\bhvs\\.[A-Za-z0-9_-]{90,}\\b", "critical", 0.95),
  P("vault_batch", "HashiCorp", "vault", "\\bhvb\\.[A-Za-z0-9_-]{90,}\\b", "critical", 0.9),
  P("nomad", "Nomad", "orchestration", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("etcd", "etcd", "kv", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("zookeeper", "ZooKeeper", "coordination", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("traefik", "Traefik", "proxy", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("envoy", "Envoy", "proxy", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("linkerd", "Linkerd", "mesh", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("istio", "Istio", "mesh", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("caddy", "Caddy", "proxy", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("nginx_auth", "Nginx", "proxy", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("haproxy", "HAProxy", "proxy", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("ssh_priv", "SSH", "key", "\\bssh-rsa [A-Za-z0-9+/=]{200,}", "high", 0.9),
  P("ssh_ed25519", "SSH", "key", "\\bssh-ed25519 [A-Za-z0-9+/=]{60,}", "high", 0.9),
  P("ssh_ecdsa", "SSH", "key", "\\becdsa-sha2-[a-z0-9]+ [A-Za-z0-9+/=]{60,}", "high", 0.9),
  P("putty", "PuTTY", "key", "\\bPuTTY-User-Key-File-[0-9]+:[\\s\\S]*?Private-MAC", "high", 0.9),
  P("wireguard", "WireGuard", "vpn", "Interface[\\s\\S]*?PrivateKey\\s*=\\s*[A-Za-z0-9+/]{43,47}=", "high", 0.9),
  P("openvpn", "OpenVPN", "vpn", "\\b[A-Za-z0-9+/]{60,}={0,2}\\b", "low", 0.2),
  P("tailscale", "Tailscale", "vpn", "\\btskey-[A-Za-z0-9_-]{40,}\\b", "high", 0.9),
  P("twingate", "Twingate", "vpn", "\\b[A-Za-z0-9_-]{40,}\\b", "low", 0.2),
  P("cloudflare_tunnel", "Cloudflare", "tunnel", "\\b[A-Za-z0-9_-]{40,}\\b", "low", 0.2),
  P("zerotier", "ZeroTier", "vpn", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("tailscale_tailnet", "Tailscale", "vpn", "\\b[A-Za-z0-9_-]{40,}\\b", "low", 0.2),
  // WireGuard keys are 32 raw bytes -> 44 base64 chars ending in "=", which is
  // the shape of ANY base64-encoded 32-byte value. As a bare
  // \b[A-Za-z0-9+/]{43,47}= this fired on unrelated base64 blobs (it was one of
  // the detectors mis-attributing an encoded Stripe key as "WireGuard").
  // Require the config key name; `wireguard` above still covers the full
  // Interface{...PrivateKey} block.
  P("wireguard_psk", "WireGuard", "vpn", "\\b(?:PresharedKey|PrivateKey)\\s*=\\s*[A-Za-z0-9+/]{42,46}=", "medium", 0.9),
  P("ipsec", "IPsec", "vpn", "\\b[A-Za-z0-9+/]{40,}={0,2}\\b", "low", 0.2),
  P("openldap", "OpenLDAP", "directory", "ldaps?://[^:\\s]+:[^@\\s]+@[\\w.-]+", "high", 0.9),
  P("active_dir", "Active Directory", "directory", "\\bLDAP://[^\\s]+['\"]?", "medium", 0.5),

  // ===== ADDITIONAL SAAS (100+) =====
  P("stripe_2024", "Stripe", "payments", "\\bstripe_secret['\"]?\\s*[:=]\\s*['\"]?sk_(live|test)_[A-Za-z0-9]{16,}['\"]?", "critical", 0.95),
  P("lemonsqueezy", "LemonSqueezy", "payments", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("gumroad", "Gumroad", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("paddle", "Paddle", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("chargebee", "Chargebee", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("chargebee_live", "Chargebee", "payments", "\\b[A-Za-z0-9_-]{40}\\b", "medium", 0.4),
  P("recurly", "Recurly", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("zuora", "Zuora", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("fusebill", "Fusebill", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("fastspring", "FastSpring", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("avangate", "Avangate", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("cleverbridge", "Cleverbridge", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("2checkout", "2Checkout", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("bluesnap", "BlueSnap", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("worldpay", "Worldpay", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("adyen", "Adyen", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("mollie", "Mollie", "payments", "\\b[A-Za-z0-9_-]{40}\\b", "medium", 0.4),
  P("klarna", "Klarna", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("afterpay", "Afterpay", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("affirm", "Affirm", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("sezzle", "Sezzle", "payments", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("shopify", "Shopify", "ecom", "\\bshpat_[A-Fa-f0-9]{32}\\b", "critical", 0.95),
  P("shopify_secret", "Shopify", "ecom", "\\bshpss_[a-fA-F0-9]{32}\\b", "high", 0.9),
  P("shopify_token", "Shopify", "ecom", "\\bshpca_[a-fA-F0-9]{32}\\b", "high", 0.9),
  P("shopify_app", "Shopify", "ecom", "\\bshppa_[a-fA-F0-9]{32}\\b", "high", 0.9),
  P("woocommerce", "WooCommerce", "ecom", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("magento", "Magento", "ecom", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("bigcommerce", "BigCommerce", "ecom", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("wix", "Wix", "web", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("squarespace", "Squarespace", "web", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("webflow", "Webflow", "web", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("framer", "Framer", "web", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("wordpress", "WordPress", "cms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("ghost", "Ghost", "cms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("contentful", "Contentful", "cms", "\\b[A-Za-z0-9_-]{43}\\b", "medium", 0.4),
  P("storyblok", "Storyblok", "cms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("sanity", "Sanity", "cms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("strapi", "Strapi", "cms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("prismic", "Prismic", "cms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("builderio", "Builder.io", "cms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("cloudinary", "Cloudinary", "media", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("cloudinary_url", "Cloudinary", "media", "cloudinary://[0-9]+:[A-Za-z0-9_-]+@[A-Za-z0-9_-]+", "high", 0.9),
  P("imgix", "Imgix", "media", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("mux", "Mux", "video", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("mux_token", "Mux", "video", "\\b[A-Za-z0-9_-]{40}\\b", "medium", 0.4),
  P("cloudflare_stream", "Cloudflare", "video", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("videojs", "Video.js", "video", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("youtube_api", "YouTube", "api", "\\bAIza[0-9A-Za-z_-]{35}\\b", "high", 0.85),
  P("vimeo", "Vimeo", "video", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("twilio_subaccount", "Twilio", "sms", "\\bSK[a-z0-9]{32}\\b", "high", 0.9),
  // MessageBird access keys are 25 alphanumeric chars with NO distinctive prefix,
  // so the old pattern was a bare `\b[A-Za-z0-9_-]{25}\b`. That matched any
  // 25-character run — including the base64 chunks inside an OpenSSH PRIVATE KEY
  // block (base64's `+` and `/` act as word boundaries), producing a flood of
  // false "MessageBird" hits on every PEM file. Require the identifying key name,
  // exactly as aws_secret_key does, and drop `_-` from the value charset.
  P("messagebird", "MessageBird", "sms", "\\bmessagebird[_-]?(?:access[_-]?key|api[_-]?key|key|token)?['\"]?\\s*[:=]\\s*['\"]?[A-Za-z0-9]{25}\\b", "medium", 0.9),
  P("vonage", "Vonage", "sms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("plivo", "Plivo", "sms", "\\b[A-Za-z0-9_-]{40}\\b", "medium", 0.4),
  P("bandwidth", "Bandwidth", "sms", "\\b[A-Za-z0-9_-]{40}\\b", "medium", 0.4),
  P("telesign", "Telesign", "sms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("sinch", "Sinch", "sms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("clickatell", "Clickatell", "sms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("nexmo", "Nexmo", "sms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("bandwidth_voice", "Bandwidth", "voice", "\\b[A-Za-z0-9_-]{40}\\b", "medium", 0.4),
  P("agora", "Agora", "voice", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("dailyco", "Daily.co", "video", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("whereby", "Whereby", "video", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("twilio_video", "Twilio", "video", "\\bSK[a-z0-9]{32}\\b", "high", 0.85),
  P("aws_chime", "AWS", "video", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("aws_ivs", "AWS", "video", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("aws_mediaconvert", "AWS", "media", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("aws_mediapackage", "AWS", "media", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("aws_mediatailor", "AWS", "media", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("aws_polly", "AWS", "ai", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("aws_rekognition", "AWS", "ai", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("aws_textract", "AWS", "ai", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("aws_transcribe", "AWS", "ai", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("aws_translate", "AWS", "ai", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("aws_comprehend", "AWS", "ai", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("aws_bedrock", "AWS", "ai", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("aws_sagemaker", "AWS", "ai", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("azure_ai", "Azure", "ai", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("azure_cognitive", "Azure", "ai", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("azure_openai", "Azure", "ai", "\\b[A-Za-z0-9_-]{32}\\b", "medium", 0.4),
  P("azure_speech", "Azure", "ai", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("azure_vision", "Azure", "ai", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("gcp_vision", "Google", "ai", "\\bAIza[0-9A-Za-z_-]{35}\\b", "high", 0.8),
  P("gcp_speech", "Google", "ai", "\\bAIza[0-9A-Za-z_-]{35}\\b", "high", 0.8),
  P("gcp_natural_language", "Google", "ai", "\\bAIza[0-9A-Za-z_-]{35}\\b", "high", 0.8),
  P("gcp_translation", "Google", "ai", "\\bAIza[0-9A-Za-z_-]{35}\\b", "high", 0.8),
  P("gcp_dialogflow", "Google", "ai", "\\bAIza[0-9A-Za-z_-]{35}\\b", "high", 0.8),
  P("ibm_watson", "IBM", "ai", "\\b(?:ibm|watson)[A-Za-z0-9_.-]*[\\'\"]?\\s*[:=]\\s*[\\'\"]?[A-Za-z0-9_-]{44}", "medium", 0.9),
  P("ibm_cloud", "IBM", "cloud", "\\b(?:ibm|watson)[A-Za-z0-9_.-]*[\\'\"]?\\s*[:=]\\s*[\\'\"]?[A-Za-z0-9_-]{44}", "medium", 0.85),
  P("oracle_cloud", "Oracle", "cloud", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("alibaba", "Alibaba Cloud", "cloud", "\\bLTAI[A-Za-z0-9]{12,}\\b", "high", 0.85),
  P("tencent", "Tencent Cloud", "cloud", "\\bAKID[A-Za-z0-9]{13,}\\b", "high", 0.85),
  P("huawei", "Huawei Cloud", "cloud", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("baidu", "Baidu Cloud", "cloud", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("wasabi_access", "Wasabi", "storage", "\\b[A-Za-z0-9_-]{20}\\b", "low", 0.2),
  P("digitalocean_spaces", "DigitalOcean", "storage", "\\bdo_v1_[a-f0-9]{64}\\b", "high", 0.8),
  P("linode_obj", "Linode", "storage", "\\b(?:linode)[A-Za-z0-9_.-]*[\\'\"]?\\s*[:=]\\s*[\\'\"]?[a-f0-9]{64}", "medium", 0.85),
  P("backblaze_key", "Backblaze", "storage", "\\b005[A-Za-z0-9_-]{30}\\b", "high", 0.85),

  // ===== ANALYTICS/CRM (30+) =====
  P("amplitude", "Amplitude", "analytics", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("mixpanel", "Mixpanel", "analytics", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("segment", "Segment", "analytics", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("heap", "Heap", "analytics", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("hotjar", "Hotjar", "analytics", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("fullstory", "FullStory", "analytics", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("logrocket", "LogRocket", "analytics", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("mouseflow", "Mouseflow", "analytics", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("luckyorange", "LuckyOrange", "analytics", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("matomo", "Matomo", "analytics", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("posthog", "PostHog", "analytics", "\\bphc_[A-Za-z0-9_-]{43}\\b", "high", 0.9),
  P("posthog_proj", "PostHog", "analytics", "\\bphs_[A-Za-z0-9_-]{43}\\b", "high", 0.85),
  P("posthog_personal", "PostHog", "analytics", "\\bphx_[A-Za-z0-9_-]{43}\\b", "high", 0.85),
  P("google_analytics", "Google", "analytics", "\\bUA-[0-9]+-[0-9]+\\b", "low", 0.3),
  P("google_analytics4", "Google", "analytics", "\\bG-[A-Z0-9]{6,}\\b", "low", 0.3),
  P("google_tag", "Google", "analytics", "\\bGTM-[A-Z0-9]{6,}\\b", "low", 0.3),
  P("salesforce", "Salesforce", "crm", "\\b00D[A-Za-z0-9]{12,}\\b", "high", 0.85),
  P("salesforce_oauth", "Salesforce", "crm", "\\b00D[A-Za-z0-9]{12,}![A-Za-z0-9]{40}\\b", "critical", 0.9),
  P("zendesk", "Zendesk", "support", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("freshdesk", "Freshdesk", "support", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("intercom_token", "Intercom", "support", "\\bdG7[A-Za-z0-9_-]{57}\\b", "high", 0.85),
  P("helpscout", "HelpScout", "support", "\\b[A-Za-z0-9_-]{40}\\b", "medium", 0.4),
  P("livechat", "LiveChat", "support", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("olark", "Olark", "support", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("drift", "Drift", "support", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("tawk", "Tawk.to", "support", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("crisp", "Crisp", "support", "\\b[A-Za-z0-9_-]{40}\\b", "medium", 0.4),
  P("snapengage", "SnapEngage", "support", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("zopim", "Zopim", "support", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("userlike", "Userlike", "support", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),

  // ===== DEV/API PLATFORMS (40+) =====
  P("postman", "Postman", "dev", "\\bPMAK-[A-Za-z0-9_-]{59}\\b", "high", 0.9),
  P("vercel_token_v2", "Vercel", "deploy", "\\b[A-Za-z0-9]{24}\\b", "medium", 0.3),
  P("supabase_service", "Supabase", "database", "\\beyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\b", "medium", 0.5),
  P("supabase_anon_v2", "Supabase", "database", "\\beyJ[A-Za-z0-9_-]{10,}\\.eyJ[A-Za-z0-9_-]{10,}\\.[A-Za-z0-9_-]{10,}\\b", "medium", 0.5),
  P("hasura", "Hasura", "graphql", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("apollo", "Apollo", "graphql", "\\bservice:[A-Za-z0-9_-]{40,}@", "high", 0.85),
  P("graphql_studio", "Apollo", "graphql", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("prisma_data", "Prisma", "database", "\\bprisma://[A-Za-z0-9_-]+:[A-Za-z0-9_-]+@", "high", 0.9),
  P("planetscale_token", "PlanetScale", "database", "\\bpscale_tkn_[A-Za-z0-9_-]{32}\\b", "high", 0.9),
  P("neon_token", "Neon", "database", "\\b[A-Za-z0-9_-]{40}\\b", "medium", 0.4),
  P("xata", "Xata", "database", "\\bxau_[A-Za-z0-9_-]{40,}\\b", "high", 0.85),
  P("convex", "Convex", "database", "\\b[A-Za-z0-9_-]{40}\\b", "medium", 0.4),
  P("fauna", "Fauna", "database", "\\bfn[A-Za-z0-9_-]{40,}\\b", "high", 0.85),
  P("appwrite", "Appwrite", "backend", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("supabase_v3", "Supabase", "backend", "\\b[A-Za-z0-9_-]{40}\\b", "medium", 0.4),
  P("nhost", "Nhost", "backend", "\\b[A-Za-z0-9_-]{40}\\b", "medium", 0.4),
  P("edge_db", "EdgeDB", "database", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("surreal", "SurrealDB", "database", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("cockroach_token", "CockroachDB", "database", "\\b[A-Za-z0-9_-]{40}\\b", "medium", 0.4),
  P("tidb", "TiDB", "database", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("yugabyte", "YugabyteDB", "database", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("scylla", "ScyllaDB", "database", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("clickhouse", "ClickHouse", "database", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("druid", "Apache Druid", "database", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("pinot", "Apache Pinot", "database", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("trino", "Trino", "database", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("presto", "Presto", "database", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("databricks", "Databricks", "data", "\\bdapi[A-Za-z0-9_-]{28,}\\b", "high", 0.9),
  P("snowflake", "Snowflake", "data", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("bigquery", "Google", "data", "\\b[A-Za-z0-9_-]{40}\\b", "medium", 0.4),
  P("athena", "AWS", "data", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("redshift", "AWS", "data", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("glue", "AWS", "data", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("kinesis", "AWS", "data", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("firehose", "AWS", "data", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("lambda", "AWS", "compute", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("ecs", "AWS", "compute", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("eks", "AWS", "compute", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("ecr", "AWS", "registry", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("cloudfront", "AWS", "cdn", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("route53", "AWS", "dns", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("ses_smtp", "AWS", "email", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("sns", "AWS", "messaging", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("sqs", "AWS", "queue", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("eventbridge", "AWS", "events", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("step_functions", "AWS", "workflow", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("amplify", "AWS", "frontend", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("cognito", "AWS", "auth", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("cognito_pool", "AWS", "auth", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("location", "AWS", "geo", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("iot_core", "AWS", "iot", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("greengrass", "AWS", "iot", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("deepracer", "AWS", "ml", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("robomaker", "AWS", "robotics", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("braket", "AWS", "quantum", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("ground_station", "AWS", "satellite", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),

  // ===== ENTROPY-BASED DETECTION (catches unknown secrets) =====
  P("entropy_40", "HighEntropy", "unknown", "\\b[A-Za-z0-9+/=_-]{40,}\\b", "medium", 0.3),
  P("entropy_32", "HighEntropy", "unknown", "\\b[A-Za-z0-9+/=_-]{32,39}\\b", "low", 0.2),
  P("hex_32", "HexToken", "unknown", "\\b[a-f0-9]{32}\\b", "low", 0.2),
  P("hex_64", "HexToken", "unknown", "\\b[a-f0-9]{64}\\b", "medium", 0.4),
  P("hex_40", "HexToken", "unknown", "\\b[a-f0-9]{40}\\b", "low", 0.3),
  P("base64_long", "Base64", "unknown", "\\b[A-Za-z0-9+/]{60,}={0,2}\\b", "low", 0.2),
  P("uuid", "UUID", "unknown", "\\b[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\b", "low", 0.15),
  P("connection_string_generic", "Generic", "database", "(?:server|host|hostname|datasource)['\"]?\\s*[:=]\\s*['\"]?[a-zA-Z0-9.-]+;(?:user|uid|username)['\"]?\\s*[:=]\\s*['\"]?[a-zA-Z0-9_-]+;(?:password|pwd|pass)['\"]?\\s*[:=]\\s*['\"]?[^'\";]+", "high", 0.8),

  // ===== ADDITIONAL PROVIDERS — 70+ more to reach 500+ total =====
  // Security/Auth
  P("auth0", "Auth0", "auth", "\\b(?:auth0)[A-Za-z0-9_.-]*[\\'\"]?\\s*[:=]\\s*[\\'\"]?[A-Za-z0-9_-]{40,}", "medium", 0.85),
  P("okta", "Okta", "auth", "\\b(?:okta[A-Za-z0-9_.-]*[\\'\"]?\\s*[:=]\\s*[\\'\"]?|SSWS\\s+)00[A-Za-z0-9_-]{15,}", "medium", 0.9),
  P("auth0_client", "Auth0", "auth", "\\b(?:auth0)[A-Za-z0-9_.-]*[\\'\"]?\\s*[:=]\\s*[\\'\"]?[A-Za-z0-9_-]{32}", "medium", 0.85),
  P("auth0_secret", "Auth0", "auth", "\\b(?:auth0)[A-Za-z0-9_.-]*[\\'\"]?\\s*[:=]\\s*[\\'\"]?[A-Za-z0-9_-]{48,}", "medium", 0.9),
  P("keycloak", "Keycloak", "auth", "\\b[A-Za-z0-9_-]{36}\\b", "low", 0.2),
  P("fusionauth", "FusionAuth", "auth", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("supertokens", "SuperTokens", "auth", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("clerk", "Clerk", "auth", "\\bsk_(test|live)_[A-Za-z0-9]{24,}\\b", "high", 0.85),
  P("stytch", "Stytch", "auth", "\\bsecret-(test|live)-[A-Za-z0-9_-]{36}\\b", "high", 0.85),
  P("workos", "WorkOS", "auth", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("frontegg", "Frontegg", "auth", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("descope", "Descope", "auth", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("magic", "Magic", "auth", "\\bsk_(test|live)_[A-Fa-f0-9]{32}\\b", "high", 0.85),
  P("privy", "Privy", "auth", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("dynamic", "Dynamic", "auth", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  // CDN/Edge
  P("bunnycdn", "Bunny CDN", "cdn", "\\b(?:bunny(?:cdn)?)[A-Za-z0-9_.-]*[\\'\"]?\\s*[:=]\\s*[\\'\"]?[a-f0-9]{32}", "medium", 0.85),
  P("keycdn", "KeyCDN", "cdn", "\\b[A-Za-z0-9_-]{24}\\b", "low", 0.2),
  P("stackpath", "StackPath", "cdn", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("bunnycdn_storage", "Bunny CDN", "storage", "\\b(?:bunny(?:cdn)?)[A-Za-z0-9_.-]*[\\'\"]?\\s*[:=]\\s*[\\'\"]?[A-Za-z0-9_-]{40}", "medium", 0.9),
  P("edgio", "Edgio", "cdn", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  // DNS/Domain
  P("namecheap", "Namecheap", "dns", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("godaddy", "GoDaddy", "dns", "\\b[A-Za-z0-9_-]{9}\\b", "low", 0.2),
  P("cloudflare_dns", "Cloudflare", "dns", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("route53_v2", "AWS", "dns", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("dnsimple", "DNSimple", "dns", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("linode_dns", "Linode", "dns", "\\b(?:linode)[A-Za-z0-9_.-]*[\\'\"]?\\s*[:=]\\s*[\\'\"]?[A-Za-z0-9_-]{32}", "medium", 0.85),
  // Email delivery
  P("mailersend", "MailerSend", "email", "\\bmlsn\\.[a-f0-9]{32}\\b", "high", 0.85),
  P("mailtrap", "Mailtrap", "email", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("mailgun_v2", "Mailgun", "email", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("mailjet_v2", "Mailjet", "email", "\\b[A-Za-z0-9]{32}\\b", "low", 0.2),
  P("elastic_v2", "ElasticEmail", "email", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("amazonses_v2", "AWS", "email", "\\b[A-Za-z0-9_-]{40}\\b", "low", 0.2),
  P("postmark_v2", "Postmark", "email", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("smtp2go", "SMTP2Go", "email", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("smtp", "SMTP", "email", "smtps?://[^:\\s]+:[^@\\s]+@[\\w.-]+", "high", 0.9),
  // Forms/Surveys
  P("typeform_v2", "Typeform", "forms", "\\btfp_[A-Za-z0-9_-]{40,}\\b", "high", 0.9),
  P("fillout", "Fillout", "forms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("tally", "Tally", "forms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("formspree", "Formspree", "forms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("formspark", "FormSpark", "forms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("getform", "Getform", "forms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("formsubmit", "FormSubmit", "forms", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  // Project Management
  P("linear_v2", "Linear", "pm", "\\blin_api_[A-Za-z0-9]{40}\\b", "high", 0.9),
  P("asana_v2", "Asana", "pm", "\\b[0-9]/[0-9]+:[A-Za-z0-9]+\\b", "medium", 0.5),
  P("monday", "Monday", "pm", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("clickup", "ClickUp", "pm", "\\bpk_[0-9]{8}_[A-Z0-9]{32}\\b", "high", 0.85),
  P("notion_v3", "Notion", "pm", "\\bsecret_[A-Za-z0-9]{43}\\b", "high", 0.9),
  P("basecamp", "Basecamp", "pm", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("teamwork", "Teamwork", "pm", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("wrike", "Wrike", "pm", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("smartsheet", "Smartsheet", "pm", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("ganttpro", "GanttPRO", "pm", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  // Booking/Calendar
  P("calendly_v2", "Calendly", "calendar", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("cal_com", "Cal.com", "calendar", "\\bcal_[A-Za-z0-9_-]{32}\\b", "high", 0.85),
  P("acuity", "Acuity", "calendar", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("squarespace_v2", "Squarespace", "calendar", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("oncehub", "OnceHub", "calendar", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("schedulista", "Schedulista", "calendar", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("simplybook", "SimplyBook", "calendar", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("booqable", "Booqable", "calendar", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  // Maps/Geo
  P("mapbox", "Mapbox", "geo", "\\bpk\\.[A-Za-z0-9]{60,}\\b", "high", 0.9),
  P("google_maps", "Google", "geo", "\\bAIza[0-9A-Za-z_-]{35}\\b", "high", 0.85),
  P("mapbox_sk", "Mapbox", "geo", "\\bsk\\.[A-Za-z0-9]{60,}\\b", "critical", 0.95),
  P("mapbox_token", "Mapbox", "geo", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("here", "HERE", "geo", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("tomtom", "TomTom", "geo", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("openrouteservice", "OpenRouteService", "geo", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("geocodio", "Geocodio", "geo", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("mapquest", "MapQuest", "geo", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
  P("opencage", "OpenCage", "geo", "\\b[A-Za-z0-9_-]{32}\\b", "low", 0.2),
]

export const PATTERN_COUNT = SECRET_PATTERNS.length
