// @shadowpaste/security — encrypted vault + credential injection
// Real AES-GCM-256 encrypted storage. AI agents NEVER receive raw secrets.
// Flow: Claude asks "use GitHub" → ShadowPaste checks identity/permission/policy
//       → mints a scoped, time-limited capability token → injects the real secret
//       into the tool adapter ONLY for the duration of execution → secret is
//       redacted from audit logs → token is consumed (single-use).

import { db } from "@/lib/db";
import { aesEncrypt, aesDecrypt, deriveAesKeyFromPassphrase, importHmacKey, randomBytes, bufToB64, sha256Hex } from "./crypto";
import { CapabilityEngine, type CapabilityToken } from "./capability";
import { classifyProvider, providerLabel } from "./detector";
import { promises as fs } from "fs";
import path from "path";

// ---- Vault master key ------------------------------------------------------
// The vault key is DERIVED (PBKDF2-SHA256, 210k iterations) from a persisted
// master passphrase — never randomly generated per process. The previous design
// silently destroyed every vaulted secret on restart, because the only key able
// to decrypt the stored ciphertext died with the process.
//
// Sourcing order:
//   1. SHADOWPASTE_MASTER_KEY from the environment.
//   2. Otherwise, on first boot, generate a 256-bit passphrase and append it to
//      the local .env so later boots derive the SAME key.
//
// Only the passphrase and its (non-secret) salt are persisted. The derived AES
// key itself is never written to disk.

const ENV_KEY = "SHADOWPASTE_MASTER_KEY";
const ENV_SALT = "SHADOWPASTE_VAULT_SALT";

let _vaultKey: CryptoKey | null = null;
let _capEngine: CapabilityEngine | null = null;
let _warnedEphemeral = false;

async function readEnvFile(): Promise<Record<string, string>> {
  try {
    const raw = await fs.readFile(path.resolve(process.cwd(), ".env"), "utf8");
    const out: Record<string, string> = {};
    for (const line of raw.split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Za-z0-9_]+)\s*=\s*(.*?)\s*$/);
      if (m) out[m[1]] = m[2];
    }
    return out;
  } catch {
    return {};
  }
}

async function appendEnvFile(pairs: Record<string, string>): Promise<boolean> {
  if (!Object.keys(pairs).length) return true;
  const file = path.resolve(process.cwd(), ".env");
  const body =
    `\n# --- auto-generated by ShadowPaste on first boot - DO NOT COMMIT ---\n` +
    `# Derives the AES-GCM-256 vault key. Losing this makes every vaulted secret\n` +
    `# permanently unrecoverable. Back it up alongside your other secrets.\n` +
    Object.entries(pairs).map(([k, v]) => `${k}=${v}`).join("\n") + "\n";
  try {
    await fs.appendFile(file, body, "utf8");
    return true;
  } catch {
    return false;
  }
}

/** Resolve (and on first boot, provision) the master passphrase + salt. */
async function resolveMasterMaterial(): Promise<{ passphrase: string; salt: string }> {
  const fileEnv = await readEnvFile();
  let passphrase = process.env[ENV_KEY] || fileEnv[ENV_KEY] || "";
  let salt = process.env[ENV_SALT] || fileEnv[ENV_SALT] || "";
  if (passphrase && salt) return { passphrase, salt };

  const generated: Record<string, string> = {};
  if (!passphrase) { passphrase = bufToB64(randomBytes(32)); generated[ENV_KEY] = passphrase; }
  if (!salt) { salt = bufToB64(randomBytes(16)); generated[ENV_SALT] = salt; }

  const persisted = await appendEnvFile(generated);
  if (!persisted) {
    // Read-only filesystem (e.g. a container). Without persistence the key would
    // be ephemeral again, so fail loudly rather than silently losing data later.
    if (process.env.NODE_ENV === "production") {
      throw new Error(
        `${ENV_KEY} is not set and .env is not writable. Set ${ENV_KEY} (openssl rand -base64 32) ` +
        `and ${ENV_SALT} explicitly, or every vaulted secret will be destroyed on restart.`
      );
    }
    if (!_warnedEphemeral) {
      _warnedEphemeral = true;
      console.warn(
        `[vault] Could not persist ${ENV_KEY} to .env - the vault key is EPHEMERAL for this ` +
        `process and vaulted secrets will NOT survive a restart.`
      );
    }
  }
  process.env[ENV_KEY] = passphrase;
  process.env[ENV_SALT] = salt;
  return { passphrase, salt };
}

export async function getVaultKey(): Promise<CryptoKey> {
  if (_vaultKey) return _vaultKey;
  const { passphrase, salt } = await resolveMasterMaterial();
  const { key } = await deriveAesKeyFromPassphrase(passphrase, salt);
  return (_vaultKey = key);
}

export async function getCapabilityEngine(): Promise<CapabilityEngine> {
  if (!_capEngine) {
    // Derived from the same master material (domain-separated) so capability
    // tokens stay verifiable across restarts instead of silently invalidating.
    const { passphrase } = await resolveMasterMaterial();
    const hmacKey = await importHmacKey(`${passphrase}:capability-hmac`);
    _capEngine = new CapabilityEngine(hmacKey);
  }
  return _capEngine;
}

// ---- Vault entry storage ----
// Secrets are stored encrypted in the VaultEntry table. The raw value lives only
// in memory during a tool call and is NEVER returned to the client or written to
// audit logs in plaintext.

export interface StoredSecret {
  id: string;
  name: string;
  provider: string;
  scope: string;
  fingerprint: string; // sha256 of raw, for dedup
  masked: string;
  encrypted: { iv: number[]; cipher: string };
  createdAt: Date;
}

export async function storeSecret(raw: string, opts: { name?: string; contextHint?: string; orgId?: string; projectId?: string } = {}): Promise<StoredSecret> {
  const key = await getVaultKey();
  const encrypted = await aesEncrypt(key, raw);
  const { provider, scope } = providerLabel(raw, opts.contextHint || "");
  const fingerprint = await sha256Hex(raw);
  const masked = raw.length <= 12 ? raw.slice(0, 4) + "***" : raw.slice(0, 8) + "..." + raw.slice(-4);
  const name = opts.name || `${provider}_${fingerprint.slice(0, 8)}`;

  const row = await db.vaultEntry.create({
    data: {
      name,
      provider,
      scope,
      fingerprint,
      masked,
      encryptedIv: JSON.stringify(encrypted.iv),
      encryptedCipher: encrypted.cipher,
      orgId: opts.orgId || "default",
      projectId: opts.projectId || null,
    },
  });

  return {
    id: row.id,
    name: row.name,
    provider: row.provider,
    scope: row.scope,
    fingerprint: row.fingerprint,
    masked: row.masked,
    encrypted,
    createdAt: row.createdAt,
  };
}

export async function retrieveSecret(id: string): Promise<string | null> {
  const key = await getVaultKey();
  const row = await db.vaultEntry.findUnique({ where: { id } });
  if (!row) return null;
  try {
    return await aesDecrypt(key, { iv: JSON.parse(row.encryptedIv), cipher: row.encryptedCipher });
  } catch {
    return null;
  }
}

export async function listSecrets(orgId = "default"): Promise<Array<{ id: string; name: string; provider: string; scope: string; masked: string; fingerprint: string; createdAt: Date }>> {
  const rows = await db.vaultEntry.findMany({ where: { orgId }, orderBy: { createdAt: "desc" } });
  return rows.map((r) => ({ id: r.id, name: r.name, provider: r.provider, scope: r.scope, masked: r.masked, fingerprint: r.fingerprint, createdAt: r.createdAt }));
}

// Delete a vault entry. When orgId is provided the delete is tenant-scoped so
// a secret can only be removed by its owning org; returns whether a row was
// actually deleted.
export async function deleteSecret(id: string, orgId?: string): Promise<boolean> {
  if (orgId) {
    const res = await db.vaultEntry.deleteMany({ where: { id, orgId } });
    return res.count > 0;
  }
  await db.vaultEntry.delete({ where: { id } });
  return true;
}

// ---- Credential injection for tool calls ----
// Given a tool scope (e.g. "github.repo") and a session, find a matching vaulted
// secret, mint a single-use capability token, and return BOTH the raw secret
// (for the tool adapter only) and the token (for audit). The raw secret must
// never be logged.

export interface InjectedCredential {
  token: CapabilityToken;
  raw: string;        // ONLY for the tool adapter; never log this
  secretId: string;
  provider: string;
  scope: string;
}

export async function injectCredential(opts: {
  sessionId: string;
  scope: string;            // e.g. "github.repo", "stripe.charges"
  orgId?: string;
  ttlMs?: number;
}): Promise<InjectedCredential | null> {
  const orgId = opts.orgId || "default";
  // Find a vaulted secret matching the requested scope (prefix match)
  const row = await db.vaultEntry.findFirst({
    where: { orgId, scope: { startsWith: opts.scope.split(".")[0] } },
    orderBy: { createdAt: "desc" },
  });
  if (!row) return null;

  const key = await getVaultKey();
  const raw = await aesDecrypt(key, { iv: JSON.parse(row.encryptedIv), cipher: row.encryptedCipher });
  if (!raw) return null;

  const engine = await getCapabilityEngine();
  const token = await engine.mint({
    secretId: row.id,
    sessionId: opts.sessionId,
    scope: opts.scope,
    action: opts.scope,
    ttlMs: opts.ttlMs ?? 5 * 60 * 1000,
    oneTime: true,
    usageLimit: 1,
  });

  return { token, raw, secretId: row.id, provider: row.provider, scope: row.scope };
}

/**
 * Consume a capability token and REPORT the outcome.
 *
 * Enforcement mode is deliberately staged. Until this change the ledger was
 * write-only: `consume()` recorded a nonce and nothing ever read it, so replay
 * protection existed in the code and not in the running system. Turning it
 * straight on would introduce a denial path that has never executed in
 * production — if some flow consumes a token twice today, it succeeds silently
 * and would begin failing without warning.
 *
 * So the default is LOG-ONLY: a rejected consume fires a critical alert and the
 * call proceeds. Set CAPABILITY_ENFORCE=true to make it deny. The intent is to
 * run log-only for one release, confirm the alert stays silent under real
 * traffic, and then flip it — rather than discovering the answer from an
 * incident.
 */
export async function consumeCredential(
  token: CapabilityToken,
  context: { tool?: string; agentId?: string; orgId?: string } = {}
): Promise<{ ok: boolean; why?: string; enforced: boolean }> {
  const engine = await getCapabilityEngine();
  const r = await engine.consume(token);
  const enforcing = process.env.CAPABILITY_ENFORCE === "true";

  if (!r.ok) {
    // Fire-and-forget: an alerting failure must never break the tool call that
    // triggered it. Imported lazily so the security layer does not depend on
    // observability at module load.
    void import("@/lib/observability/alerts")
      .then(({ fireAlert }) =>
        fireAlert({
          rule: "security.capability_replay",
          severity: "critical",
          title: "Capability token rejected at consume",
          description: `${r.why} (mode: ${enforcing ? "ENFORCING" : "log-only"})`,
          dedupeKey: `capability_replay:${context.agentId ?? token.sessionId}`,
          context: {
            reason: r.why,
            scope: token.scope,
            sessionId: token.sessionId,
            tool: context.tool,
            agentId: context.agentId,
            orgId: context.orgId,
            enforcing,
          },
        })
      )
      .catch(() => {});
  }

  return { ...r, enforced: enforcing };
}

// ---- Redaction for audit logs ----
// Replaces any raw secret value in an arbitrary string with its vault reference.
export function redactSecrets(text: string, secrets: Array<{ raw: string; reference: string }>): string {
  let out = text;
  for (const s of secrets) {
    if (s.raw && s.raw.length > 4) {
      out = out.split(s.raw).join(s.reference);
    }
  }
  return out;
}

// Scan arbitrary text for secrets and auto-vault any found (used by scanner + file tools).
export async function scanAndVault(text: string, opts: { orgId?: string; projectId?: string; contextHint?: string } = {}): Promise<{ text: string; vaulted: number; findings: Array<{ provider: string; reference: string }> }> {
  const { scanForSecrets, virtualizeText } = await import("./detector");
  const findings = scanForSecrets(text, opts.contextHint);
  if (findings.length === 0) return { text, vaulted: 0, findings: [] };

  const refs: Array<{ raw: string; reference: string }> = [];
  for (const f of findings) {
    const stored = await storeSecret(f.raw, { orgId: opts.orgId, projectId: opts.projectId, contextHint: opts.contextHint });
    refs.push({ raw: f.raw, reference: `{{SHADOW_SECRET_${stored.provider}_${stored.id.slice(-5)}}}` });
  }
  const redacted = redactSecrets(text, refs);
  return {
    text: redacted,
    vaulted: findings.length,
    findings: refs.map((r) => ({ provider: classifyProvider(r.raw).provider, reference: r.reference })),
  };
}
