"use client"
import { useEffect, useState } from "react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Label } from "@/components/ui/label"
import { toast } from "sonner"
import { api, RiskBadge, DecisionBadge, timeLabel } from "./shared"
import { Network, Play, Shield, Cpu, AlertTriangle, CheckCircle2, XCircle, Clock, Zap, ArrowRight, Activity, Boxes } from "lucide-react"

interface Tool { id: string; name: string; category: string; description: string; riskLevel: "low" | "medium" | "high" | "critical"; riskScore: number; packageName: string }
interface Agent { id: string; name: string; provider: string; trustScore: number; status: string }
interface CallResult {
  ok: boolean; decision: string; reason: string; policy: string; riskScore: number; riskLevel: "low" | "medium" | "high" | "critical"
  auditRequired: boolean; toolCallId: string; output: Record<string, unknown> | null
  factors: Array<{ factor: string; weight: number; description: string }>; inputFlags: string[]; durationMs: number
}

const SAMPLE_INPUTS: Record<string, string> = {
  "fs.read": '{\n  "path": "/app/src/server.ts"\n}',
  "fs.write": '{\n  "path": "/app/src/server.ts",\n  "content": "console.log(\\"patched\\")"\n}',
  "github.read": '{\n  "repo": "acme/platform"\n}',
  "github.pr.create": '{\n  "repo": "acme/platform",\n  "title": "AI: add caching layer",\n  "body": "Generated by Claude Code"\n}',
  "github.repo.delete": '{\n  "repo": "acme/prod-frontend"\n}',
  "db.read": '{\n  "query": "SELECT * FROM users LIMIT 10"\n}',
  "db.schema.drop": '{\n  "target": "public"\n}',
  "db.export": '{\n  "table": "users"\n}',
  "shell.exec": '{\n  "command": "rm -rf /tmp/cache"\n}',
  "stripe.charge": '{\n  "amount": 9999,\n  "currency": "usd"\n}',
}

export function McpGateway() {
  const [tools, setTools] = useState<Tool[]>([])
  const [agents, setAgents] = useState<Agent[]>([])
  const [agentId, setAgentId] = useState("")
  const [toolName, setToolName] = useState("")
  const [input, setInput] = useState("{}")
  const [calling, setCalling] = useState(false)
  const [result, setResult] = useState<CallResult | null>(null)
  const [history, setHistory] = useState<CallResult[]>([])

  useEffect(() => {
    api<{ tools: Tool[] }>("/api/mcp/tools").then((d) => { setTools(d.tools); if (d.tools[0]) { setToolName(d.tools[0].name); setInput(SAMPLE_INPUTS[d.tools[0].name] || "{}") } })
    api<{ agents: Agent[] }>("/api/agents").then((d) => { setAgents(d.agents); if (d.agents[0]) setAgentId(d.agents[0].id) })
  }, [])

  const selectedTool = tools.find((t) => t.name === toolName)
  const selectedAgent = agents.find((a) => a.id === agentId)

  const onToolChange = (name: string) => {
    setToolName(name)
    setInput(SAMPLE_INPUTS[name] || "{}")
    setResult(null)
  }

  const call = async () => {
    if (!agentId || !toolName) return
    setCalling(true)
    try {
      let parsed = {}
      try { parsed = JSON.parse(input) } catch { toast.error("Invalid JSON input"); setCalling(false); return }
      const res = await api<CallResult>("/api/mcp/call", { method: "POST", body: JSON.stringify({ agentId, toolName, input: parsed }) })
      setResult(res)
      setHistory((h) => [res, ...h].slice(0, 12))
      if (res.decision === "deny") toast.error(`DENIED — ${res.reason}`)
      else if (res.decision === "sandbox") toast.info(`SANDBOXED — ${res.reason}`)
      else if (res.decision === "ask") toast.warning(`Approval required — ${res.reason}`)
      else toast.success(`ALLOWED — ${res.reason}`)
    } catch (e) {
      toast.error((e as Error).message)
    } finally {
      setCalling(false)
    }
  }

  const categories = [...new Set(tools.map((t) => t.category))]

  return (
    <div className="space-y-6">
      {/* Architecture diagram */}
      <Card className="border-white/5 bg-[#0d1218] p-5">
        <div className="mb-4 flex items-center gap-2">
          <Network className="h-4 w-4 text-emerald-400" />
          <h3 className="font-mono text-sm font-semibold text-white">Zero-Trust MCP Gateway Flow</h3>
        </div>
        <div className="flex flex-wrap items-center gap-2 text-[11px]">
          {["AI Agent", "ShadowPaste Gateway", "Policy Engine", "Secure Execution", "Audit Record"].map((step, i, arr) => (
            <div key={step} className="flex items-center gap-2">
              <div className={`rounded-lg border px-3 py-1.5 font-mono ${i === 1 ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-300" : "border-white/10 bg-white/[0.03] text-zinc-300"}`}>
                {step}
              </div>
              {i < arr.length - 1 && <ArrowRight className="h-3 w-3 text-zinc-600" />}
            </div>
          ))}
        </div>
      </Card>

      <div className="grid gap-6 lg:grid-cols-5">
        {/* Left: invocation console */}
        <div className="space-y-4 lg:col-span-3">
          <Card className="border-white/5 bg-[#0d1218] p-5">
            <div className="mb-4 flex items-center gap-2">
              <Cpu className="h-4 w-4 text-emerald-400" />
              <h3 className="font-mono text-sm font-semibold text-white">Tool Invocation Console</h3>
            </div>
            <div className="space-y-4">
              <div>
                <Label className="text-[11px] uppercase tracking-wider text-zinc-400">AI Agent</Label>
                <Select value={agentId} onValueChange={setAgentId}>
                  <SelectTrigger className="mt-1 border-white/10 bg-white/[0.03] font-mono text-sm"><SelectValue placeholder="Select agent" /></SelectTrigger>
                  <SelectContent className="border-white/10 bg-[#0d1218]">
                    {agents.map((a) => (
                      <SelectItem key={a.id} value={a.id} className="font-mono">
                        <span className="flex items-center gap-2">
                          <span className={`h-1.5 w-1.5 rounded-full ${a.status === "active" ? "bg-emerald-400" : "bg-red-400"}`} />
                          {a.name} · trust {a.trustScore}
                        </span>
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label className="text-[11px] uppercase tracking-wider text-zinc-400">MCP Tool</Label>
                <Select value={toolName} onValueChange={onToolChange}>
                  <SelectTrigger className="mt-1 border-white/10 bg-white/[0.03] font-mono text-sm"><SelectValue placeholder="Select tool" /></SelectTrigger>
                  <SelectContent className="border-white/10 bg-[#0d1218] max-h-72">
                    {categories.map((cat) => (
                      <div key={cat}>
                        <div className="px-2 py-1 text-[10px] uppercase tracking-wider text-zinc-500">{cat}</div>
                        {tools.filter((t) => t.category === cat).map((t) => (
                          <SelectItem key={t.id} value={t.name} className="font-mono">
                            <span className="flex items-center gap-2">
                              <RiskBadge level={t.riskLevel} />
                              {t.name}
                            </span>
                          </SelectItem>
                        ))}
                      </div>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              {selectedTool && (
                <div className="rounded-lg border border-white/5 bg-white/[0.02] p-3">
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-xs text-zinc-400">{selectedTool.packageName}</span>
                    <RiskBadge level={selectedTool.riskLevel} score={selectedTool.riskScore} />
                  </div>
                  <p className="mt-1 text-xs text-zinc-300">{selectedTool.description}</p>
                </div>
              )}
              <div>
                <Label className="text-[11px] uppercase tracking-wider text-zinc-400">Input Payload (JSON)</Label>
                <Textarea value={input} onChange={(e) => setInput(e.target.value)} rows={5} className="mt-1 border-white/10 bg-[#070a0f] font-mono text-xs text-emerald-300" />
              </div>
              <Button onClick={call} disabled={calling} className="w-full bg-emerald-600 text-white hover:bg-emerald-500">
                {calling ? <><Clock className="mr-2 h-4 w-4 animate-spin" /> Routing through gateway…</> : <><Play className="mr-2 h-4 w-4" /> Invoke Through Gateway</>}
              </Button>
            </div>
          </Card>

          {/* Result */}
          {result && (
            <Card className="border-white/5 bg-[#0d1218] p-5">
              <div className="mb-3 flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Shield className="h-4 w-4 text-emerald-400" />
                  <h3 className="font-mono text-sm font-semibold text-white">Gateway Decision</h3>
                </div>
                <DecisionBadge decision={result.decision} />
              </div>
              <div className="space-y-3">
                <div className={`rounded-lg border p-3 ${result.decision === "deny" ? "border-red-500/30 bg-red-500/[0.07]" : result.decision === "sandbox" ? "border-violet-500/30 bg-violet-500/[0.07]" : result.decision === "ask" ? "border-amber-500/30 bg-amber-500/[0.07]" : "border-emerald-500/30 bg-emerald-500/[0.07]"}`}>
                  <div className="flex items-center gap-2">
                    {result.decision === "deny" ? <XCircle className="h-4 w-4 text-red-400" /> : result.decision === "sandbox" ? <Boxes className="h-4 w-4 text-violet-400" /> : result.decision === "ask" ? <AlertTriangle className="h-4 w-4 text-amber-400" /> : <CheckCircle2 className="h-4 w-4 text-emerald-400" />}
                    <span className="text-sm font-semibold text-white">{result.reason}</span>
                  </div>
                </div>
                <div className="grid gap-2 sm:grid-cols-2 text-xs">
                  <Field label="Policy" value={result.policy} mono />
                  <Field label="Risk Score" value={`${result.riskScore}/100 · ${result.riskLevel}`} mono />
                  <Field label="Latency" value={`${result.durationMs}ms`} mono />
                  <Field label="Audit Required" value={result.auditRequired ? "YES" : "no"} mono />
                </div>
                {result.inputFlags.length > 0 && (
                  <div>
                    <div className="mb-1 text-[10px] uppercase tracking-wider text-amber-400">Input Risk Flags</div>
                    <div className="flex flex-wrap gap-1.5">
                      {result.inputFlags.map((f) => <Badge key={f} variant="outline" className="border-amber-500/30 bg-amber-500/10 text-[10px] text-amber-300">{f}</Badge>)}
                    </div>
                  </div>
                )}
                {result.factors.length > 0 && (
                  <div>
                    <div className="mb-1 text-[10px] uppercase tracking-wider text-zinc-500">Risk Factors</div>
                    <div className="space-y-1">
                      {result.factors.map((f, i) => (
                        <div key={i} className="flex items-center justify-between rounded bg-white/[0.02] px-2 py-1 text-[11px]">
                          <span className="text-zinc-300">{f.factor}</span>
                          <span className={`font-mono ${f.weight > 0 ? "text-red-400" : "text-emerald-400"}`}>{f.weight > 0 ? "+" : ""}{f.weight}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
                {result.output && (
                  <div>
                    <div className="mb-1 text-[10px] uppercase tracking-wider text-zinc-500">Execution Output</div>
                    <pre className="overflow-x-auto rounded-lg border border-white/5 bg-[#070a0f] p-3 font-mono text-[11px] text-emerald-300">{JSON.stringify(result.output, null, 2)}</pre>
                  </div>
                )}
              </div>
            </Card>
          )}
        </div>

        {/* Right: tool registry + call history */}
        <div className="space-y-4 lg:col-span-2">
          <Card className="border-white/5 bg-[#0d1218] p-5">
            <div className="mb-3 flex items-center justify-between">
              <div className="flex items-center gap-2"><Zap className="h-4 w-4 text-emerald-400" /><h3 className="font-mono text-sm font-semibold text-white">Quick Test Scenarios</h3></div>
            </div>
            <div className="space-y-2">
              {[
                { label: "Safe read (low risk)", tool: "fs.read", agent: true, color: "emerald" },
                { label: "Open a PR (medium)", tool: "github.pr.create", agent: true, color: "amber" },
                { label: "DROP TABLE (critical)", tool: "db.schema.drop", agent: true, color: "red" },
                { label: "Delete prod repo (critical)", tool: "github.repo.delete", agent: true, color: "red" },
                { label: "Rogue agent attempt", tool: "db.export", agent: false, color: "violet" },
              ].map((s) => (
                <button key={s.label} onClick={() => {
                  const a = s.agent ? agents.find((x) => x.status === "active") : agents.find((x) => x.status === "quarantined" || x.trustScore < 40)
                  if (a) setAgentId(a.id)
                  onToolChange(s.tool)
                }} className="flex w-full items-center justify-between rounded-lg border border-white/5 bg-white/[0.02] px-3 py-2 text-left text-xs transition-colors hover:bg-white/[0.04]">
                  <span className="text-zinc-300">{s.label}</span>
                  <ArrowRight className="h-3 w-3 text-zinc-600" />
                </button>
              ))}
            </div>
          </Card>

          <Card className="border-white/5 bg-[#0d1218] p-5">
            <div className="mb-3 flex items-center gap-2"><Activity className="h-4 w-4 text-emerald-400" /><h3 className="font-mono text-sm font-semibold text-white">Session Call History</h3></div>
            <div className="max-h-96 space-y-1.5 overflow-y-auto pr-1" style={{ scrollbarWidth: "thin" }}>
              {history.length === 0 && <div className="rounded-lg border border-dashed border-white/5 py-6 text-center text-xs text-zinc-500">No calls in this session yet.</div>}
              {history.map((h, i) => (
                <div key={i} className="rounded-lg border border-white/5 bg-white/[0.02] px-3 py-2">
                  <div className="flex items-center justify-between">
                    <DecisionBadge decision={h.decision} />
                    <span className="font-mono text-[10px] text-zinc-500">{timeLabel(new Date(Date.now() - i * 1000).toISOString())}</span>
                  </div>
                  <div className="mt-1 truncate text-[11px] text-zinc-400">{h.reason}</div>
                  <div className="mt-1 flex items-center gap-2">
                    <RiskBadge level={h.riskLevel} score={h.riskScore} />
                    <span className="font-mono text-[10px] text-zinc-500">{h.durationMs}ms</span>
                  </div>
                </div>
              ))}
            </div>
          </Card>
        </div>
      </div>
    </div>
  )
}

function Field({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="rounded-lg border border-white/5 bg-white/[0.02] px-3 py-2">
      <div className="text-[10px] uppercase tracking-wider text-zinc-500">{label}</div>
      <div className={`mt-0.5 text-xs text-zinc-200 ${mono ? "font-mono" : ""}`}>{value}</div>
    </div>
  )
}


